name: 'Build Openwrt Firmware'
description: 'Build openwrt firmware with ease'
inputs:
  config:  # id of input
    description: 'Config file name without ".sh". "all" to build all.'
    required: true
    default: 'all'
runs:
  using: "composite"
  steps:
    - run: bash build.sh ./configs/${{ inputs.config }}-openwrt.sh
      shell: bash