# This is a basic workflow to help you get started with Actions

name: Build - ARM64

# Controls when the workflow will run
on:
  repository_dispatch:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * 5'

env:
  TZ: 'Asia/Shanghai'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CONFIG: arm64-openwrt
    steps:
      - name: Start ${{ env.CONFIG }} Compile
        uses: ./.github/actions/my-action
        with:
          config: ${{ env.CONFIG }}