name: Repo Dispatcher
on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Input config script file name without ".sh". "all" to build all the configs.'
        required: false
        default: 'all'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Trigger Compile
          run: |
            curl \
            -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"event_type": "${{ github.event.inputs.config }}", "client_payload": {"config": "${{ github.event.inputs.config }}"}}'
